### ISSUE TITLE
WSL / Update info "This may be due to lack of SYSV IPC support"

### ISSUE THREAD

**Issue by vviikk** [vviikk/vviikk.github.io#3]
```shell
✖ Making for target: deb - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: deb
Error executing command (Exited with status 1):
fakeroot dpkg-deb --build /tmp/electron-119020-1753-srkzys.1j6dg/mnm_1.0.0_amd64
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
/usr/bin/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]

Error: Error executing command (Exited with status 1):
fakeroot dpkg-deb --build /tmp/electron-119020-1753-srkzys.1j6dg/mnm_1.0.0_amd64
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
/usr/bin/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]

    at spawn.then.catch.err (/mnt/c/Users/piggy/play/mnm/node_modules/electron-installer-debian/src/spawn.js:31:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```
Fix was:
```
 sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp
```

**Comment by vviikk** [comment]
Info in this comment:
https://github.com/Microsoft/WSL/issues/2465#issuecomment-377583291
